sudo: required
services:
    - docker

before_install:
    - docker build -t alexsus87/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true alexsus87/react-test npm test

after_success:
    - docker build -t alexsus87/multi-client ./client
    - docker build -t alexsus87/multi-nginx ./nginx
    - docker build -t alexsus87/multi-server ./server
    - docker build -t alexsus87/multi-worker ./worker
    # log in to docker cli
    - exho "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push images to docker hub
    - docker push alexsus87/multi-client 
    - docker push alexsus87/multi-nginx
    - docker push alexsus87/multi-server
    - docker push alexsus87/multi-worker